# coding: utf-8
get_ipython().magic('run cnn_birds.py')
get_ipython().magic('whos ')
get_ipython().magic('pinfo train_datagen')
get_ipython().magic('whos ')
get_ipython().magic('run cnn_birds.py')
get_ipython().magic('run cnn_birds.py')
get_ipython().magic('run cnn_birds.py')
get_ipython().magic('run cnn_birds.py')
get_ipython().magic('run cnn_birds.py')
get_ipython().magic('run cnn_birds.py')
get_ipython().magic('run cnn_birds.py')
get_ipython().magic('run cnn_birds.py')
get_ipython().magic('run cnn_birds.py')
get_ipython().magic('run cnn_birds.py')
get_ipython().magic('run cnn_birds.py')
get_ipython().magic('run cnn_birds.py')
get_ipython().magic('run cnn_birds.py')
get_ipython().magic('run cnn_birds.py')
get_ipython().magic('run cnn_birds.py')
get_ipython().magic('run cnn_birds.py')
model.evaluate_generator()
model.evaluate_generator(X_train_gen,X_test_gen)
get_ipython().magic('pinfo model.evaluate_generator')
model.evaluate_generator(X_train_gen)
model.evaluate_generator(X_train_gen,steps=5)
model.metrics_names
model.metrics_names
get_ipython().magic('run cnn_birds.py')
model.metrics_names
model.evaluate_generator(X_train_gen,steps=5)
get_ipython().magic('run cnn_birds.py')
model.metrics_names
model.evaluate_generator(X_train_gen,steps=5)
get_ipython().magic('run cnn_birds.py')
get_ipython().magic('run cnn_birds.py')
model.metrics_names
model.evaluate_generator(X_train_gen,steps=5)
get_ipython().magic('run cnn_birds.py')
model.metrics_names
model.evaluate_generator(X_train_gen,steps=5)
get_ipython().magic('run cn_soln.py')
get_ipython().magic('run cnn_soln.py')
get_ipython().magic('run cnn_soln.py')
get_ipython().magic('run cnn_birds.py')
get_ipython().magic('run cnn_birds.py')
get_ipython().magic('run cnn_birds.py')
get_ipython().magic('run cnn_birds.py')
get_ipython().magic('run cnn_birds.py')
model.metrics_names
model.evaluate_generator(X_train_gen,steps=5)
model.summary()
get_ipython().magic('run cnn_birds.py')
model.summary()
get_ipython().magic('run cnn_birds.py')
model.summary()
model.evaluate_generator(X_train_gen,steps=5)
get_ipython().magic('run cnn_birds.py')
get_ipython().magic('run cnn_birds.py')
model.evaluate_generator(X_train_gen,steps=5)
model.metrics_names
get_ipython().magic('run cnn_birds.py')
model.metrics_names
model.evaluate_generator(X_train_gen,steps=5)
model.summary()
get_ipython().magic('pinfo model')
get_ipython().magic('pinfo model.predict_generator')
model.predict_generator(X_test_gen)
model.predict_generator(X_test_gen, steps=12)
model.evaluate_generator(X_test_gen,steps=12)
get_ipython().magic('run cnn_birds.py')
model.evaluate_generator(X_test_gen,steps=12)
import tflearn
import tflearn
get_ipython().magic('whos ')
get_ipython().magic('pinfo save')
get_ipython().magic('history ')
get_ipython().magic('save current_session ~0/')
